### ISSUE TITLE
TypeError: Cannot define property:48, object is not extensible

### ISSUE THREAD

**Issue by kl20** [LoicMahieu/PDFKitJS#3]
```
    at normalize (/Users/juanjesusc/Documents/ceramic-pro/react/node_modules/pdfkitjs/node_modules/temporary/lib/detector.js:23:34)
    at Object.detector.tmp (/Users/juanjesusc/Documents/ceramic-pro/react/node_modules/pdfkitjs/node_modules/temporary/lib/detector.js:43:10)
    at Object.generator.build (/Users/juanjesusc/Documents/ceramic-pro/react/node_modules/pdfkitjs/node_modules/temporary/lib/generator.js:45:27)
    at File.Base.init (/Users/juanjesusc/Documents/ceramic-pro/react/node_modules/pdfkitjs/node_modules/temporary/lib/base.js:31:28)
    at new File (/Users/juanjesusc/Documents/ceramic-pro/react/node_modules/pdfkitjs/node_modules/temporary/lib/file.js:23:8)
    at new PDFKit (/Users/juanjesusc/Documents/ceramic-pro/react/node_modules/pdfkitjs/lib/pdfkit.js:49:19)
```

Upgrading to `temporary-0.0.8` fixes it.

**Comment by LoicMahieu** [comment]
Thanks for your issue. This project is not maintained anymore, please use https://github.com/devongovett/node-wkhtmltopdf
